spring:
  datasource:
    url: jdbc:h2:mem:invoice-register-database;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      path: /console
      enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

logging:
  level:
    org.hibernate: INFO

server:
  port: 8080

properties:
  vat: 15